run_tests:
  image: python:3.10-bullseye
  before_script:
    - pip install flake8 pytest pytest-cov
    - pip install -r requirements.txt
  script:
    - pytest -v --cov

.include_terraform_template: &include_terraform_template
  before_script:
    - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip terraform_${TF_VERSION}_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - terraform version

include:
  - template: Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

variables:
  TF_VERSION: "1.2.0"
  TF_STATE_NAME: default
  TF_CACHE_KEY: default

fmt:
  extends:
    - .terraform:fmt
    - .include_terraform_template
  needs: []

validate:
  extends:
    - .terraform:validate
    - .include_terraform_template
  needs: []

build:
  extends:
    - .terraform:build
    - .include_terraform_template

deploy:
  extends:
    - .terraform:deploy
    - .include_terraform_template
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
