python:build:
  stage: build
  image: python:3.11
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
  script:
    - pip install -r client/requirements.txt

python:test:
  image: python:3.11
  stage: test
  script:
    - pip install -r client/requirements.txt
    - python -m unittest discover -s client -p "*_test.py"

include:
  - template: Terraform.gitlab-ci.yml

variables:
  TF_ROOT: "./terraform"
