# run_tests:
#   before_script:
#     - pip install flake8 pytest pytest-cov
#     - pip install -r requirements.txt
#   script:
#     - pytest

include:
  - template: Terraform.gitlab-ci.yml

variables: 
  TF_ROOT: "terraf"