build:
  stage: build
  image: python:3.6
  script:
    - pip install flake8 pytest pytest-cov
    - pip install -r requirements.txt

test:
  image: python:3.6
  stage: test
  script:
    - python -m unittest discover -s ./ -p '*_test.py'

include:
  - template: Terraform.gitlab-ci.yml

variables:
  TF_ROOT: "terraform"
