# run_tests:
#   before_script:
#     - pip install flake8 pytest pytest-cov
#     - pip install -r requirements.txt
#   script:
#     - pytest

stages:
  - validate
  - deploy

variables:
  TF_VERSION: "1.2.0"

.include:
  - template: Terraform/Base.gitlab-ci.yml

format_terraform:
  stage: validate
  script:
    - terraform fmt -check -recursive

deploy_terraform:
  stage: deploy
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve
