version: '3'

services: 
  client: 
    build: 
      context: ./client
    volumes: 
      - ./auth:/src/auth
    environment:
      - PYTHONUNBUFFERED=1
      - IP=a3uf1j30lr99lx-ats.iot.eu-central-1.amazonaws.com
      - PORT=8883
      - STATIONNAME=SENDER
    depends_on:
      - receiver

  receiver:
    build: 
      context: ./receiver
    volumes: 
      - ./auth:/src/auth
    environment:
      - PYTHONUNBUFFERED=1
      - IP=a3uf1j30lr99lx-ats.iot.eu-central-1.amazonaws.com
      - PORT=8883
      - STATIONNAME=RECEIVER